### ISSUE TITLE
example needs to be extended to support API 9

### ISSUE THREAD

**Issue by anujgoyal** [googlesamples/android-FloatingActionButtonBasic#1]
This sample should be extended to support API 9.  Most app developers would like to support older versions of Android as well.

```
defaultConfig {
    minSdkVersion 21   /* should be 9 */
    targetSdkVersion 21
}
```

**Comment by fernandomantoan** [comment]
I agree... But the FAB code will crash in older versions, things like `ViewOutlineProvider` for example aren't supported...

**Comment by Nutriz** [comment]
I want to add an Add action button like this exemple but i want to use minsdk 11, it is a trick to do it ? The Gmail android app have a Add button bottom right and im on Kitkat.

**Comment by chrisbanes** [comment]
The goal of this sample was to show how to use new Lollipop APIs to easily achieve a floating action button. It wasn't meant to be a fully fledged implementation of one.
