### ISSUE TITLE
Update the code to use Design Support Library

### ISSUE THREAD

**Issue by seventhmoon** [googlesamples/android-FloatingActionButtonBasic#2]
Since Design Support Library is released, suggesting a code update to use Design Support Library instead for the FAB.

**Comment by keyboardsurfer** [comment]
This sample precedes the design support library and shows how to do a FloatingActionButton on your own.
If you want guidance on extending the design library FloatingActionButton, [Topeka's source code](https://github.com/googlesamples/android-topeka/blob/master/app/src/main/java/com/google/samples/apps/topeka/widget/fab/CheckableFab.java) is a good starting point.
