### ISSUE TITLE
Can't build with Android studio 2.0

### ISSUE THREAD

**Issue by jesse-bernoudy** [googlesamples/android-FloatingActionButtonBasic#4]
I have tried to build with both Android Studio 2.0 and from the command line and I get this error:

`android-FloatingActionButtonBasic\Application\build\intermediates\exploded-aar\com.android.support\cardview-v7\23.3.0\res\values-v23\values-v23.xml:3:5-5:13: AAPT: No resource found that matches the given name (at 'cardBackgroundColor' with value '?android:attr/colorBackgroundFloating').`

My Setup:
Windows 10 x64
Android Studio 2.0 (build #AI-143.2739321)
Android SDKs 5.01 (API 21), 5.0.1 (API 21), 5.1.1 (API 22) and 6.0 (API 23)
Android SDK build tools 23.0.1, 23.0.3, 23.0.3
Android SDK Tools 23.1
Android Platform Tools 25.1.2
Android Support Library 23.2.1
Android Support Repository 30.0

**Comment by codingjeremy** [comment]
This sample has been deprecated/archived (check README for more information on newer samples related to this technology). 

[As recommended by GitHub][1], we are closing all issues and pull requests.

[1]: https://help.github.com/en/articles/archiving-repositories
